# Generated by Django 4.1.7 on 2023-03-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='exam',
            new_name='exams',
        ),
    ]
